name: Generate Readme
on: 
  push:
    branches:    
      - master
jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - run: node ./.github/main.js
      - run: chmod +x ./.github/deploy.sh
      - run: git config user.name "numandev1"
      - run: git config user.email "muhammadnuman70@gmail.com"
      - run: git add README.md
      - run: git commit -m "chore:Generate README"
      - name: Push
        run: git push --quiet "git@github.com:numandev1/open-source-react-native-apps.git"  master:master > /dev/null 2>&1
